### Listar itens do Carrinho
GET https://localhost:5001/api/item/carrinho/1 

### Cadastrar um novo item do carrinho
POST https://localhost:5001/api/item/criar
Content-Type: application/json

{
    "produtoId": 1, 
    "quantidade": 1, 
    "carrinhoId": 1
}

### Deletar um item do carrinho
DELETE https://localhost:5001/api/item/deletar/1