### Cadastrar Categoria
POST https://localhost:5001/api/categoria/cadastrar
Content-Type: application/json

{
    "Tipo": "Eletro Eletronico"
}

### Listar Clientes
GET https://localhost:5001/api/categoria/listar
